### ISSUE TITLE
Unable to Select Different Perks

### ISSUE THREAD

**Issue by GabrielePaolini** [Northfear/fallout1-ce-vita#2]
I recently installed the latest version of fallout1-ce-vita (v1.0.0-vita.2) on my PS Vita 1000 through the Vita HomeBrew Browser.
Data were copied from my steam version of the game. 
Other than changing the config file to read the correct music folder path (initially there was no music), the game run very smoothly. However, when I reached lvl 3, on the character menu, I couldn't select any perk other than the first one (Awareness). 
The directional pad wouldn't work and if I try to double click on another perk, the game simply confirm the choice of the Awareness perk. 

Has anyone encountered this problem?

**Comment by Northfear** [comment]
Can you attach the savegame, so I could look at it?

**Comment by GabrielePaolini** [comment]
Here's the latest savegame.
For the sake of clarity, I got the save from the ux0:/data/fallout/DATA/SAVEGAME/ folder.

[SLOT05.zip](https://github.com/Northfear/fallout1-ce-vita/files/13456953/SLOT05.zip)

**Comment by Northfear** [comment]
Please try the latest development version
https://github.com/Northfear/fallout1-ce-vita/releases/tag/latest

**Comment by GabrielePaolini** [comment]
With the latest release it works like a charm! Thanks a lot!
