### ISSUE TITLE
Vita command stops woking

### ISSUE THREAD

**Issue by wi3ste** [Northfear/fallout1-ce-vita#3]
I'm in junktown and after i kill gizmo i'm teleported to the entrance with lars. after the screen loads the commands just stop responding, except for the touchscreen, also i can't save or else the game just crashes on me. 
here's my save file. Currently playing on v1.0.0-vita.3
[SLOT02.zip](https://github.com/Northfear/fallout1-ce-vita/files/13762100/SLOT02.zip)

**Comment by wi3ste** [comment]
It actually happened every single time i ti got teleported. Anyway your savegame seems to work fine so thank you and happy holidays

**Comment by Northfear** [comment]
Do you have any mods installed? It's either that or some data mismatch. Or maybe some upper/lower case inconsistency and problems related to that (like patch files not loading, etc).
Either way it would be interesting to check whether it fails with PC version too.

**Comment by wi3ste** [comment]
No mods installed. I'll try to reimport all the data files from the pc to the vita and see what happens
