### ISSUE TITLE
mouse/trackpad does not lock on Ipad

### ISSUE THREAD

**Issue by BobbySauce** [Northfear/fallout1-ce-vita#6]
Hello,
if you try to use mouse on ipad it does not lock the mouse position and the OS pointer stays on screen permanentely.
Is there a way to change this? It would be such a great way to play.

thanks

**Comment by Northfear** [comment]
Hey. I'm only maintaining PS Vita version here. iPad related bugs should probably go upstream

https://github.com/alexbatalov/fallout1-ce

**Comment by BobbySauce** [comment]
> Hey. I'm only maintaining PS Vita version here. iPad related bugs should probably go upstream
> 
> https://github.com/alexbatalov/fallout1-ce
I'm sorry, I just noticed myself. Still, thank you for answering so fast
