### ISSUE TITLE
Rear Touchpad not working

### ISSUE THREAD

**Issue by vortex36** [Northfear/fallout1-ce-vita#7]
I'm trying to set the game up so that the front touch will use direct control (so FRONT_TOUCH_MODE=1) and the rear touchpad will use trackpad mode (REAR_TOUCH_MODE=2). Both 1 and 2 work correctly on front touch, but whatever value I put in rear_touch_mode besides 0 will make both the front and rear touch not work.

After trying out different things, I found out that with FRONT_TOUCH_MODE=1, REAR_TOUCH_MODE=2, if I don't touch the rear pad at all after starting the game, the front touch will work as intended, but as soon as I touch the rear pad, the mouse cursor resets back to the center of the screen and then, both front and rear touch inputs stop working. Is this intended behaviour?

**Comment by Northfear** [comment]
Hi

That's definitely not intended. Rear one might've been broken after the last touchad related updates in the game. I'll look into it once I'll have some spare time

**Comment by vortex36** [comment]
Thanks! 
As a side-note, changing the "mouse sensitivity" setting doesn't seem to make a noticeable difference, is it supposed to change the speed the cursor moves with the left analog?

**Comment by Northfear** [comment]
Should be fixed now. Sorry for the delay
https://github.com/Northfear/fallout1-ce-vita/releases/tag/v1.1.0-vita.4
