### ISSUE TITLE
 It doesn't work properly on 3.60 -  frequent crashes

### ISSUE THREAD

**Issue by eHerbaciarz** [Northfear/fallout1-ce-vita#8]
While playing on FW 3.60, there were very frequent crashes. The easiest way to trigger it was to put the console to sleep while the enemy was moving, e.g. when a rat was coming at you. At the very beginning I thought it was messing with plugins. However, after updating FW to 3.65 and installing the same plugins, the problem disappeared.

I'm uploading the crash logs for 3.60. The problem probably cannot be repaired - so you can mention in the description that on 3.60 there are frequent crashes, especially when waking up the console.

[psp2core-1716718771-0x0003492325-eboot.bin.zip](https://github.com/Northfear/fallout1-ce-vita/files/15447302/psp2core-1716718771-0x0003492325-eboot.bin.zip)

![441509756_1654105225348744_4746230048353329207_n](https://github.com/Northfear/fallout1-ce-vita/assets/10764145/370fd346-d289-4734-9cc4-7804984ebbbb)

**Comment by Northfear** [comment]
Interesting. Do you have [FdFix](https://github.com/TheOfficialFloW/FdFix) plugin installed?

**Comment by eHerbaciarz** [comment]
> Interesting. Do you have [FdFix](https://github.com/TheOfficialFloW/FdFix) plugin installed?


No - I didn't know about this plugin. Updating to 3.65 solved the problem.

However, the problem on 3.60 also occurred without putting the console to sleep/waking up - but it was easiest to trigger it this way.

**Comment by Northfear** [comment]
Putting the console to sleep/waking it up destroys the file descriptors on Vita. FdFix plugin fixes that specifically. rePatch does that too. I guess neither of those plugins were installed on 3.60.

I should update the readme with info regarding them, thanks for noticing it.

**Comment by Northfear** [comment]
Also new version should have those dialog/movie crashes fixed too
https://github.com/Northfear/fallout1-ce-vita/releases/tag/v1.1.0-vita.4
